pr: none
trigger: none

variables:
  - name: subscription_name
    value: AzureRM SvcConnection JMB-DPL-SDLZ-TST
  - group: "Terraform Vars TST"

stages:
    jobs:
    - job: checkout job
      steps:
      - step: checkout step
      - checkout: self 
      - step: deploy step
    # Deploy bicep main files
      - template: bicep-deploy.yml
        parameters:
          template_file: '$(Pipeline.Workspace)/infra/main.bicep'
          job_name: 'DeployInfra'
          deployment_scope: 'sub'
          deploy_env_name: 'tst'
          subscription: ${{ variables.subscription_name }}
          template_parameters: '--parameters environment=tst'