##This pipeline is triggered from ado_pipleine_ps_main.yml
#parameters:
#  - name: bicepBuild
#    default: infra
#  - name: location
#    default: westeurope
#  - name: svc_tst
#    default: 'AzureRM SvcConnection JMB-DPL-SDLZ-TST'
#  - name: azure_environment
#    default: tst
#
#jobs:
#  #Adding approval request for the Publish step
#  - deployment: DeployTST
#    displayName: 'Publish TST'
#    #Environment can be found in devops under environments
#    environment: ${{ parameters.azure_environment }}
#    variables:
#      - group: "Terraform Vars ${{parameters.azure_environment}}"
#      - group: "Bicep Vars ${{ parameters.azure_environment }}"
#    strategy:
#      runOnce:
#        deploy:
#          steps: 
#          - template: job/publish-bicep-job.yml
#            parameters:
#              azureSubscription: ${{parameters.svc_tst}}
#              azure_environment: ${{parameters.azure_environment}}

trigger:
- main

name: Deploy Bicep files

variables:
  vmImageName: 'ubuntu-latest'
  azureServiceConnection: 'AzureRM SvcConnection JMB-DPL-SDLZ-TST'
  #resourceGroupName: 'exampleRG'
  location: 'westeurope'
  templateFile: './infra/main.bicep'
pool:
  vmImage: $(vmImageName)

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    action: 'Create Or Update Resource Group'
    #resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(templateFile)'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'