name: Bicep-StorageAccount-demo
trigger:
- main

parameters:
  - name: location
    type: string
    default: 'westeurope'

variables:
  - name: subscription_name
    value: AzureRM SvcConnection JMB-DPL-SDLZ-TST

pool:
  vmImage: ubuntu-latest

stages:
- stage: CI
  jobs:
  - job: Build
    steps:
    - task: AzureCLI@2  
      displayName: 'build bicep artifact' 
      inputs: 
        azureSubscription: $(subscription_name) 
        scriptType: 'pscore'  
        scriptLocation: 'inlineScript'  
        inlineScript: 'az bicep build --file infra/main.bicep'

    - task: PublishBuildArtifacts@1 
      displayName: 'Publish artifact in pipeline' 
      inputs: 
        PathtoPublish: '$(Build.SourcesDirectory)/infra/main.json'  
        ArtifactName: 'finishedTemplate'  
        publishLocation: 'Container' 

- stage: CD
  variables:
  - group: "Terraform Vars TST"
  jobs:
  - deployment: biceptoAzure
    displayName: 'Deploy bicep to Azure'
    environment: 'AzureDeployment'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: 'deploy bicep template'
            inputs:
              azureSubscription: $(subscription_name) 
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                 az --version
                 az login --service-principal -u '$(contributor-app-registration-id)' -p '$(contributor-service-principal-secret)' --tenant $(tenant-id)
                 az deployment sub create `
                 --location $(location) `
                 --template-file $(Build.SourcesDirectory)/infra/main.bicep `
                 --parameters $(Build.SourcesDirectory)/infra/main.parameters.json 
       